name: "AhoyDTU bug"
description: "File a bug report"
title: "[ESP8266/ESP32/RaspberryPi] Problem Description / Beschreibung"
labels: ["bug", "needs-triage"]
assignees:
body:
  - type: markdown
    attributes:
      value: |
        "Bitte die Posting Guide lines lesen, Vorlage kopieren und ausfüllen und in Eurem Support Forum Eintrag posten."
        "Wir lesen auch gerne Deutsch, bitte fülle die u.a. Fragen aus damit wir Dir bestmöglich helfen können Danke!"
        ""
        "Please read, copy & fill in the template from our Posting Guide lines into your Support Forum post."
        "We do enjoy the english language, but we need a couple of things to best support you in your goal, please fill in all / most of the details given below. Thanks!"
  - type: markdown
    attributes:
      value: "## Hardware"
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which Hardware are you usning to run AhoyDTU on ?
      options:
        - label: ESP8266
        - label: ESP32
        - label: RaspberryPi
          required: true
  - type: textarea
    id: model
    attributes:
      label: Model name
      description: Please give us a precise description of your hardware and/or a link to the vendor
      placeholder: 
    validations:
      required: false
  - type: dropdown
    id: nrf24l01-module
    attributes:
      label: "nRF24L01+ Module"
      description: "What type of nRF24L01+ chip is on your nRF24L01+ module ?"
      multiple: true
      options:
        - "[ ] nRF24L01+ you verified this is a Plus model capable of the required 256kBit/s mode"
        - "[ ] square dot indicates original Nordic Semicon chip"
        - "[ ] round dot indicates copy-cat / counterfeit SI labs chip"
