name: "AhoyDTU bug"
description: "File a bug report"
title: "[ESP8266/ESP32/RaspberryPi] Problem Description / Beschreibung"
labels: ["bug", "needs-triage"]
assignees:
  - stefan123t
body:
  - type: markdown
    attributes:
      value: |
        Bitte die Posting Guide lines lesen, Vorlage kopieren und ausfüllen und in Eurem Support Forum Eintrag posten.
        Wir lesen auch gerne Deutsch, bitte fülle die u.a. Fragen aus damit wir Dir bestmöglich helfen können Danke!
        
        Please read, copy & fill in the template from our Posting Guide lines into your Support Forum post.
        We do enjoy the english language, but we need a couple of things to best support you in your goal, please fill in all / most of the details given below. Thanks!
  - type: markdown
    attributes:
      value: "## Hardware"
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which Hardware are you usning to run AhoyDTU on ?
      options:
        - ESP8266
        - ESP32
        - RaspberryPi
    validations:
      required: true
  - type: textarea
    id: model
    attributes:
      label: Model name
      description: Please give us a precise description of your hardware and/or a link to the vendor
      placeholder: 
    validations:
      required: false
  - type: dropdown
    id: nrf24l01-module
    attributes:
      label: nRF24L01+ Module
      description: What type of nRF24L01+ chip is on your nRF24L01+ module ?
      multiple: true
      options:
        - nRF24L01+ you verified this is a Plus model capable of the required 256kBit/s mode
        - square dot indicates original Nordic Semicon chip
        - round dot indicates copy-cat / counterfeit SI labs chip
  - type: dropdown
    id: antenna
    attributes:
      label: Antenna
      description: What type of antenna has your nRF24L01+ module ?
      options:
        - circuit Board
        - external Antenna
    validations:
      required: true
  - type: dropdown
    id: power-stabilization
    attributes:
      label: Power Stabilization
      description: What kind of power stabilization have you used for your nRF24L01+ module ?
      options:
        - noting (yet)
        - ~100uF Electrolytic Capacitor [connected between +3.3V and GND (Pin 1 & 2) of the NRF Module]
        - Voltage stabilizing motherboard
    validations:
      required: true
  - type: input
    id: software
    attributes:
      label: Software
      description: What version of our software are you running ?
      placeholder: Version: 0.5.17 Github Hash: 5402e9b
      value: Version: _._.__ Github Hash: _______
    validations:
      required: true
  - type: dropdown
    id: software
    attributes:
      label: "Build & Flash Method"
      description: What software do you use to build and flash our firmware images ?
      options:
        - ESP Tools
        - Platform IO
    validations:
      required: true
  - type: dropdown
    id: desktop-os
    attributes:
      label: Desktop
      description: Which operating system are you using on your desktop ?
      options:
        - Linux
        - Mac OS
        - Windows
    validations:
      required: true
  - type: textarea
    id: Debugging
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      placeholder: |
        - USB Serial Log (attached)
        - Setup settings (use our templates ... to be added)
      render: shell
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Connection picture
      description: 
      options:
        - label: I will attach/upload an Image of my wiring
    validations:
      required: true
