name: Ahoy Dev-Build for ESP8266/ESP32

on:
  push:
    branches: development*
    paths-ignore:
    - '**.md' # Do no build on *.md changes
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: development03
    - uses: benjlevesque/short-sha@v2.0
      id: short-sha
      with:
        length: 7

    - name: Cache Pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Setup Python
      uses: actions/setup-python@v4.3.0
      with:
        python-version: "3.x"

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Convert HTML files
      working-directory: tools/esp8266/html
      run: python convert.py

    - name: Run PlatformIO
      run: pio run -d tools/esp8266 --environment esp8266-release --environment esp8266-1m-release --environment esp32-wroom32-release

    - name: Rename Binary files
      id: rename-binary-files
      working-directory: tools/esp8266/scripts
      run: python getVersion.py

    - name: Set Version
      uses: cschleiden/replace-tokens@v1
      with:
        files: tools/esp8266/User_Manual.md
      env:
          VERSION: ${{ steps.rename-binary-files.outputs.name }}

    - name: Create Manifest
      working-directory: tools/esp8266/scripts
      run: python buildManifest.py

      #run: zip  --junk-paths ${{ steps.rename-binary-files.outputs.name }}.zip tools/esp8266/.pio/build/out/* tools/esp8266/User_Manual.md
    - name: Create Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.rename-binary-files.outputs.name }}_dev_build
        path: |
          tools/*/firmware/*
          tools/esp8266/User_Manual.md
          tools/*/json/manifest.json

        #./${{ steps.rename-binary-files.outputs.name }}.zip

